[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /opt/printer_data/run/klipper.sock

[machine]
provider: systemd_cli
validate_service: False

[authorization]
trusted_clients:
  192.168.1.0/24
  100.114.148.0/24
  127.0.0.1
cors_domains:
  http://*.local
  http://192.168.1.*
  http://100.114.148.*

[octoprint_compat]

[history]

[update_manager client mainsail]
type: web
repo: mainsail-crew/mainsail
path: /opt/printer_data/mainsail
